#!/usr/bin/env python
"""EOD analysis — process the log bundle with ONE LLM API request.

Reads data/logs/eod_bundle.txt (built by log_aggregate.py), sends it as the
docs payload of a SINGLE chat completion (stable analysis system prompt +
compressed bundle), writes the result to the brain vault as
E:\\Local\\brain\\notes\\eod-YYYY-MM-DD.md, and prints a short summary.

Exactly ONE API request by design (user requirement 2026-08-14): the bundle
is pre-aggregated + bounded, no agent loop, no follow-ups. Falls back to the
local qwen3:8b (via the shared client's local tier) if the cloud tier fails,
so the EOD report still lands at $0 if needed.
"""
from __future__ import annotations

import json
import sys
from datetime import datetime
from pathlib import Path

PA = Path(r"E:\Local\projects\personal-assistant")
BUNDLE = PA / "data" / "logs" / "eod_bundle.txt"
BRAIN_NOTES = Path(r"E:\Local\brain\notes")

ANALYSIS_SYSTEM = """You are KEN's end-of-day log analyst. You receive ONE bundle \
containing a full day of fleet logs: unified event log, ken_service log, agent logs, \
cost ledger, work queue + DLQ, event bus, watchdog alerts, memory distillation state, \
cron run statuses, and fleet report issues.

Produce a concise EOD report with EXACTLY these sections (markdown, terse):
## Summary — 2-3 lines: overall health verdict + the single most important number.
## Incidents — anything anomalous (errors, retries, dead-letters, alerts, outages). \
For each: what, when, impact, resolved? If none, state "none".
## Cost — today's calls, prompt/completion/cached tokens, est USD, and whether \
cache hits improved (compare cache_hit_tokens against prompt_tokens).
## Fleet — cron statuses, queue/DLQ state, stale or failing bots, distill progress.
## Watch — 2-4 concrete things to watch tomorrow (trends, risks, expected events).
Do NOT invent facts not in the bundle. No speculation. Terse, no fluff."""


def main() -> int:
    if not BUNDLE.exists():
        print("NO_BUNDLE — run qa/log_aggregate.py first")
        return 1
    bundle = BUNDLE.read_text(encoding="utf-8", errors="replace")[:60000]

    sys.path.insert(0, str(Path(r"E:\Local\projects\500-AI-Agents-Projects\agents")))
    from _shared import llm, prompts

    tail = prompts.dynamic_tail(
        "Analyze today's fleet logs and produce the EOD report per your instructions.",
        bundle,
    )
    try:
        report, tier = llm.chat("flash", tail, kind="analysis", max_tokens=1200)
    except Exception as e:
        print(f"CLOUD_FAIL {e} — trying local tier")
        try:
            report, tier = llm.chat("local", tail, kind="analysis", max_tokens=1200)
        except Exception as e2:
            print(f"ALL_FAIL {e2}")
            return 1

    date = datetime.now().strftime("%Y-%m-%d")
    note = BRAIN_NOTES / f"eod-{date}.md"
    header = f"# EOD Report — {date}\n\n_Generated by single API request (tier={tier}). Source: log_aggregate bundle._\n\n"
    note.write_text(header + report.strip() + "\n", encoding="utf-8")
    print(f"EOD_REPORT {note} (tier={tier})")
    print(report.strip()[:1500])
    return 0


if __name__ == "__main__":
    sys.exit(main())
